# Generated by Django 3.0.8 on 2020-09-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_info', '0003_periodtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.Teaches')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default='True')),
                ('batch_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.BatchAttendance')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.Student')),
            ],
        ),
    ]
