# Generated by Django 3.0.8 on 2020-09-12 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_info', '0004_attendance_batchattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
    ]
